version: '3.8'

services:
  db:
    image: library/postgres:latest
    restart: always
#    volumes:
#      - ./docker_postgres.sh:/docker-entrypoint-initdb.d/z_docker_postgres.sh
#      - postgres_data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    env_file:
      - .env

  redis:
    image: library/redis:latest
#    env_file:
#      - compose.env
    restart: always
    command: ["redis-server", "--appendonly", "yes", "--requirepass", $REDIS_PASSWORD]
    ports:
    - 6379:6379
#    volumes:
#      - redis_data:/data
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD

  memcache:
    image: library/memcached:latest
    ports:
    - 11211:11211

  pgAdmin:
    image: dpage/pgadmin4
    restart: always
#    volumes:
#    - pgAdmin_data:/var/lib/pgadmin
    depends_on:
      - db
    ports:
      - 16543:80
    env_file:
      - .env

#volumes:
 # postgres_data:
 # redis_data:
 # pgAdmin_data:
